In [1]:
import argparse
from utils.config import process_config


config = process_config("configs/reinforce_exp_0.json")

 THE Configuration of your experiment ..
{'agent': 'DQNAgent',
 'async_loading': True,
 'batch_size': 256,
 'checkpoint_file': 'checkpoint.pth.tar',
 'conv_filters': [16, 32, 32],
 'cuda': True,
 'data_folder': '',
 'data_loader': '',
 'data_loader_workers': 2,
 'data_mode': '',
 'eps_decay': 200,
 'eps_end': 0.05,
 'eps_start': 0.9,
 'exp_name': 'exp_1',
 'gamma': 0.999,
 'gpu_device': 0,
 'image_size': 64,
 'input_channels': 3,
 'max_epoch': 100,
 'memory_capacity': 10000,
 'num_classes': 2,
 'num_episodes': 100,
 'pin_memory': True,
 'screen_width': 600,
 'seed': 1337,
 'target_update': 10,
 'validate_every': 2,
 'x_test': '',
 'x_train': '',
 'x_valid': '',
 'y_test': '',
 'y_train': '',
 'y_valid': ''}
 *************************************** 


In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
import torch
a=torch.tensor((1,3,4,5,1,2,3))

In [ ]:
discounted_rewards=[]
GAMMA=0.8
for t in range(len(a)):
    Gt = 0 
    pw = 0
    for r in a[t:]:
        Gt = Gt + GAMMA**pw * r
        pw = pw + 1
    discounted_rewards.append(Gt)

In [ ]:
discounted_rewards

In [ ]:
3*0.8+2

In [3]:
from agents.reinforce import REINFORCEAgent
from agents.dqn import DQNAgent
import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore")

    test=DQNAgent(config)
    test.train()





100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [01:36<00:00,  1.04it/s]


In [ ]:
test.env.close() 

In [ ]:

import torch.nn as nn

In [ ]:
softmax=nn.Softmax(dim=1)

In [ ]:
test=torch.rand((3,2))

In [ ]:
softmax(torch.tensor((test)))

In [2]:
import warnings
from agents.reinforce import REINFORCEAgent

with warnings.catch_warnings():
    
    warnings.simplefilter("ignore")

    test=REINFORCEAgent(config)
    test.train()


  1%|▊                                                                                 | 1/100 [00:03<05:54,  3.58s/it]

tensor([ 1.5803,  1.3837,  1.1870,  0.9900,  0.7929,  0.5956,  0.3980,  0.2003,
         0.0024, -0.1957, -0.3941, -0.5926, -0.7913, -0.9902, -1.1894, -1.3887,
        -1.5882])


  2%|█▋                                                                                | 2/100 [00:04<04:23,  2.69s/it]

tensor([ 1.5948,  1.4186,  1.2422,  1.0657,  0.8890,  0.7121,  0.5350,  0.3577,
         0.1803,  0.0027, -0.1751, -0.3531, -0.5312, -0.7096, -0.8881, -1.0668,
        -1.2456, -1.4247, -1.6039])


  3%|██▍                                                                               | 3/100 [00:04<03:15,  2.01s/it]

tensor([ 1.5880,  1.4021,  1.2161,  1.0299,  0.8435,  0.6570,  0.4702,  0.2833,
         0.0962, -0.0912, -0.2787, -0.4664, -0.6542, -0.8423, -1.0306, -1.2190,
        -1.4076, -1.5964])


  4%|███▎                                                                              | 4/100 [00:04<02:23,  1.49s/it]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


  5%|████                                                                              | 5/100 [00:05<01:49,  1.15s/it]

tensor([ 1.5619,  1.3397,  1.1173,  0.8947,  0.6719,  0.4489,  0.2256,  0.0021,
        -0.2216, -0.4456, -0.6697, -0.8941, -1.1187, -1.3436, -1.5686])


  6%|████▉                                                                             | 6/100 [00:05<01:34,  1.00s/it]

tensor([ 1.6310,  1.5066,  1.3821,  1.2574,  1.1326,  1.0077,  0.8826,  0.7575,
         0.6322,  0.5068,  0.3812,  0.2555,  0.1297,  0.0038, -0.1222, -0.2484,
        -0.3747, -0.5011, -0.6277, -0.7544, -0.8812, -1.0081, -1.1352, -1.2624,
        -1.3897, -1.5171, -1.6447])


  7%|█████▋                                                                            | 7/100 [00:06<01:14,  1.26it/s]

tensor([ 1.5378,  1.2825,  1.0268,  0.7710,  0.5148,  0.2584,  0.0018, -0.2551,
        -0.5123, -0.7697, -1.0274, -1.2853, -1.5435])


  8%|██████▌                                                                           | 8/100 [00:06<01:02,  1.47it/s]

tensor([ 1.5803,  1.3837,  1.1870,  0.9900,  0.7929,  0.5956,  0.3980,  0.2003,
         0.0024, -0.1957, -0.3941, -0.5926, -0.7913, -0.9902, -1.1894, -1.3887,
        -1.5882])


  9%|███████▍                                                                          | 9/100 [00:06<00:51,  1.76it/s]

tensor([ 1.5229,  1.2469,  0.9707,  0.6942,  0.4174,  0.1403, -0.1371, -0.4147,
        -0.6926, -0.9708, -1.2492, -1.5280])
tensor([ 1.6710,  1.6113,  1.5516,  1.4918,  1.4319,  1.3720,  1.3120,  1.2520,
         1.1919,  1.1318,  1.0716,  1.0113,  0.9509,  0.8906,  0.8301,  0.7696,
         0.7090,  0.6484,  0.5877,  0.5269,  0.4661,  0.4052,  0.3443,  0.2833,
         0.2222,  0.1611,  0.0999,  0.0387, -0.0226, -0.0840, -0.1454, -0.2069,
        -0.2685, -0.3301, -0.3918, -0.4535, -0.5153, -0.5772, -0.6391, -0.7011,
        -0.7631, -0.8253, -0.8874, -0.9497, -1.0120, -1.0743, -1.1367, -1.1992,
        -1.2618, -1.3244, -1.3871, -1.4498, -1.5126, -1.5754, -1.6384, -1.7014])


 11%|████████▉                                                                        | 11/100 [00:08<01:01,  1.45it/s]

tensor([ 1.5619,  1.3397,  1.1173,  0.8947,  0.6719,  0.4489,  0.2256,  0.0021,
        -0.2216, -0.4456, -0.6697, -0.8941, -1.1187, -1.3436, -1.5686])
tensor([ 1.6686,  1.6043,  1.5399,  1.4754,  1.4109,  1.3462,  1.2816,  1.2168,
         1.1520,  1.0872,  1.0222,  0.9572,  0.8922,  0.8270,  0.7619,  0.6966,
         0.6313,  0.5659,  0.5004,  0.4349,  0.3693,  0.3037,  0.2380,  0.1722,
         0.1063,  0.0404, -0.0256, -0.0916, -0.1577, -0.2239, -0.2901, -0.3565,
        -0.4228, -0.4893, -0.5558, -0.6224, -0.6890, -0.7557, -0.8225, -0.8893,
        -0.9562, -1.0232, -1.0903, -1.1574, -1.2246, -1.2918, -1.3591, -1.4265,
        -1.4939, -1.5615, -1.6290, -1.6967])


 13%|██████████▌                                                                      | 13/100 [00:10<01:06,  1.30it/s]

tensor([ 1.6010,  1.4335,  1.2658,  1.0979,  0.9299,  0.7617,  0.5934,  0.4249,
         0.2562,  0.0873, -0.0817, -0.2509, -0.4203, -0.5898, -0.7595, -0.9294,
        -1.0995, -1.2697, -1.4401, -1.6106])


 14%|███████████▎                                                                     | 14/100 [00:10<00:56,  1.52it/s]

tensor([ 1.5803,  1.3837,  1.1870,  0.9900,  0.7929,  0.5956,  0.3980,  0.2003,
         0.0024, -0.1957, -0.3941, -0.5926, -0.7913, -0.9902, -1.1894, -1.3887,
        -1.5882])


 15%|████████████▏                                                                    | 15/100 [00:11<00:45,  1.85it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 16%|████████████▉                                                                    | 16/100 [00:11<00:45,  1.87it/s]

tensor([ 1.6116,  1.4591,  1.3065,  1.1537,  1.0008,  0.8478,  0.6945,  0.5411,
         0.3876,  0.2339,  0.0801, -0.0739, -0.2281, -0.3824, -0.5368, -0.6914,
        -0.8462, -1.0011, -1.1562, -1.3114, -1.4668, -1.6224])


 17%|█████████████▊                                                                   | 17/100 [00:12<00:37,  2.21it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 18%|██████████████▌                                                                  | 18/100 [00:12<00:34,  2.39it/s]

tensor([ 1.5507,  1.3131,  1.0752,  0.8371,  0.5988,  0.3602,  0.1214, -0.1176,
        -0.3569, -0.5964, -0.8362, -1.0762, -1.3164, -1.5569])


 19%|███████████████▍                                                                 | 19/100 [00:12<00:30,  2.69it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 20%|████████████████▏                                                                | 20/100 [00:12<00:25,  3.11it/s]

tensor([ 1.4274,  1.0204,  0.6130,  0.2051, -0.2031, -0.6118, -1.0208, -1.4303])


 21%|█████████████████                                                                | 21/100 [00:13<00:29,  2.70it/s]

tensor([ 1.6010,  1.4335,  1.2658,  1.0979,  0.9299,  0.7617,  0.5934,  0.4249,
         0.2562,  0.0873, -0.0817, -0.2509, -0.4203, -0.5898, -0.7595, -0.9294,
        -1.0995, -1.2697, -1.4401, -1.6106])


 22%|█████████████████▊                                                               | 22/100 [00:13<00:26,  2.96it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 23%|██████████████████▋                                                              | 23/100 [00:13<00:26,  2.96it/s]

tensor([ 1.5507,  1.3131,  1.0752,  0.8371,  0.5988,  0.3602,  0.1214, -0.1176,
        -0.3569, -0.5964, -0.8362, -1.0762, -1.3164, -1.5569])


 24%|███████████████████▍                                                             | 24/100 [00:14<00:24,  3.11it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 25%|████████████████████▎                                                            | 25/100 [00:14<00:23,  3.24it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 26%|█████████████████████                                                            | 26/100 [00:14<00:21,  3.37it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 27%|█████████████████████▊                                                           | 27/100 [00:15<00:22,  3.21it/s]

tensor([ 1.5507,  1.3131,  1.0752,  0.8371,  0.5988,  0.3602,  0.1214, -0.1176,
        -0.3569, -0.5964, -0.8362, -1.0762, -1.3164, -1.5569])


 28%|██████████████████████▋                                                          | 28/100 [00:15<00:20,  3.49it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 29%|███████████████████████▍                                                         | 29/100 [00:15<00:21,  3.26it/s]

tensor([ 1.5507,  1.3131,  1.0752,  0.8371,  0.5988,  0.3602,  0.1214, -0.1176,
        -0.3569, -0.5964, -0.8362, -1.0762, -1.3164, -1.5569])


 30%|████████████████████████▎                                                        | 30/100 [00:16<00:21,  3.23it/s]

tensor([ 1.5378,  1.2825,  1.0268,  0.7710,  0.5148,  0.2584,  0.0018, -0.2551,
        -0.5123, -0.7697, -1.0274, -1.2853, -1.5435])


 31%|█████████████████████████                                                        | 31/100 [00:16<00:19,  3.58it/s]

tensor([ 1.4274,  1.0204,  0.6130,  0.2051, -0.2031, -0.6118, -1.0208, -1.4303])


 32%|█████████████████████████▉                                                       | 32/100 [00:16<00:19,  3.51it/s]

tensor([ 1.5229,  1.2469,  0.9707,  0.6942,  0.4174,  0.1403, -0.1371, -0.4147,
        -0.6926, -0.9708, -1.2492, -1.5280])


 33%|██████████████████████████▋                                                      | 33/100 [00:16<00:17,  3.76it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 34%|███████████████████████████▌                                                     | 34/100 [00:17<00:19,  3.47it/s]

tensor([ 1.5507,  1.3131,  1.0752,  0.8371,  0.5988,  0.3602,  0.1214, -0.1176,
        -0.3569, -0.5964, -0.8362, -1.0762, -1.3164, -1.5569])


 35%|████████████████████████████▎                                                    | 35/100 [00:17<00:17,  3.63it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 36%|█████████████████████████████▏                                                   | 36/100 [00:17<00:17,  3.65it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 37%|█████████████████████████████▉                                                   | 37/100 [00:17<00:17,  3.56it/s]

tensor([ 1.5229,  1.2469,  0.9707,  0.6942,  0.4174,  0.1403, -0.1371, -0.4147,
        -0.6926, -0.9708, -1.2492, -1.5280])


 38%|██████████████████████████████▊                                                  | 38/100 [00:18<00:19,  3.17it/s]

tensor([ 1.5716,  1.3631,  1.1543,  0.9453,  0.7361,  0.5267,  0.3171,  0.1072,
        -0.1028, -0.3131, -0.5235, -0.7342, -0.9451, -1.1562, -1.3675, -1.5790])


 39%|███████████████████████████████▌                                                 | 39/100 [00:18<00:18,  3.35it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 40%|████████████████████████████████▍                                                | 40/100 [00:19<00:21,  2.73it/s]

tensor([ 1.6116,  1.4591,  1.3065,  1.1537,  1.0008,  0.8478,  0.6945,  0.5411,
         0.3876,  0.2339,  0.0801, -0.0739, -0.2281, -0.3824, -0.5368, -0.6914,
        -0.8462, -1.0011, -1.1562, -1.3114, -1.4668, -1.6224])


 41%|█████████████████████████████████▏                                               | 41/100 [00:19<00:20,  2.88it/s]

tensor([ 1.5229,  1.2469,  0.9707,  0.6942,  0.4174,  0.1403, -0.1371, -0.4147,
        -0.6926, -0.9708, -1.2492, -1.5280])


 42%|██████████████████████████████████                                               | 42/100 [00:19<00:18,  3.17it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 43%|██████████████████████████████████▊                                              | 43/100 [00:19<00:18,  3.06it/s]

tensor([ 1.5507,  1.3131,  1.0752,  0.8371,  0.5988,  0.3602,  0.1214, -0.1176,
        -0.3569, -0.5964, -0.8362, -1.0762, -1.3164, -1.5569])


 44%|███████████████████████████████████▋                                             | 44/100 [00:20<00:19,  2.85it/s]

tensor([ 1.5716,  1.3631,  1.1543,  0.9453,  0.7361,  0.5267,  0.3171,  0.1072,
        -0.1028, -0.3131, -0.5235, -0.7342, -0.9451, -1.1562, -1.3675, -1.5790])


 45%|████████████████████████████████████▍                                            | 45/100 [00:20<00:17,  3.19it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 46%|█████████████████████████████████████▎                                           | 46/100 [00:20<00:17,  3.11it/s]

tensor([ 1.5507,  1.3131,  1.0752,  0.8371,  0.5988,  0.3602,  0.1214, -0.1176,
        -0.3569, -0.5964, -0.8362, -1.0762, -1.3164, -1.5569])


 47%|██████████████████████████████████████                                           | 47/100 [00:21<00:16,  3.13it/s]

tensor([ 1.5378,  1.2825,  1.0268,  0.7710,  0.5148,  0.2584,  0.0018, -0.2551,
        -0.5123, -0.7697, -1.0274, -1.2853, -1.5435])


 48%|██████████████████████████████████████▉                                          | 48/100 [00:21<00:15,  3.34it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 49%|███████████████████████████████████████▋                                         | 49/100 [00:21<00:14,  3.44it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 50%|████████████████████████████████████████▌                                        | 50/100 [00:22<00:16,  3.09it/s]

tensor([ 1.5803,  1.3837,  1.1870,  0.9900,  0.7929,  0.5956,  0.3980,  0.2003,
         0.0024, -0.1957, -0.3941, -0.5926, -0.7913, -0.9902, -1.1894, -1.3887,
        -1.5882])


 51%|█████████████████████████████████████████▎                                       | 51/100 [00:22<00:14,  3.34it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 52%|██████████████████████████████████████████                                       | 52/100 [00:22<00:16,  2.93it/s]

tensor([ 1.5880,  1.4021,  1.2161,  1.0299,  0.8435,  0.6570,  0.4702,  0.2833,
         0.0962, -0.0912, -0.2787, -0.4664, -0.6542, -0.8423, -1.0306, -1.2190,
        -1.4076, -1.5964])


 53%|██████████████████████████████████████████▉                                      | 53/100 [00:23<00:16,  2.86it/s]

tensor([ 1.5619,  1.3397,  1.1173,  0.8947,  0.6719,  0.4489,  0.2256,  0.0021,
        -0.2216, -0.4456, -0.6697, -0.8941, -1.1187, -1.3436, -1.5686])


 54%|███████████████████████████████████████████▋                                     | 54/100 [00:23<00:18,  2.51it/s]

tensor([ 1.6065,  1.4469,  1.2871,  1.1272,  0.9670,  0.8068,  0.6463,  0.4857,
         0.3250,  0.1640,  0.0030, -0.1583, -0.3197, -0.4813, -0.6430, -0.8049,
        -0.9669, -1.1291, -1.2915, -1.4541, -1.6168])


 55%|████████████████████████████████████████████▌                                    | 55/100 [00:23<00:16,  2.80it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 56%|█████████████████████████████████████████████▎                                   | 56/100 [00:24<00:13,  3.19it/s]

tensor([ 1.4274,  1.0204,  0.6130,  0.2051, -0.2031, -0.6118, -1.0208, -1.4303])


 57%|██████████████████████████████████████████████▏                                  | 57/100 [00:24<00:12,  3.39it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 58%|██████████████████████████████████████████████▉                                  | 58/100 [00:24<00:11,  3.51it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 59%|███████████████████████████████████████████████▊                                 | 59/100 [00:25<00:12,  3.33it/s]

tensor([ 1.5507,  1.3131,  1.0752,  0.8371,  0.5988,  0.3602,  0.1214, -0.1176,
        -0.3569, -0.5964, -0.8362, -1.0762, -1.3164, -1.5569])


 60%|████████████████████████████████████████████████▌                                | 60/100 [00:25<00:11,  3.34it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 61%|█████████████████████████████████████████████████▍                               | 61/100 [00:25<00:11,  3.46it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 62%|██████████████████████████████████████████████████▏                              | 62/100 [00:25<00:11,  3.29it/s]

tensor([ 1.5507,  1.3131,  1.0752,  0.8371,  0.5988,  0.3602,  0.1214, -0.1176,
        -0.3569, -0.5964, -0.8362, -1.0762, -1.3164, -1.5569])


 63%|███████████████████████████████████████████████████                              | 63/100 [00:26<00:11,  3.29it/s]

tensor([ 1.5229,  1.2469,  0.9707,  0.6942,  0.4174,  0.1403, -0.1371, -0.4147,
        -0.6926, -0.9708, -1.2492, -1.5280])


 64%|███████████████████████████████████████████████████▊                             | 64/100 [00:26<00:10,  3.32it/s]

tensor([ 1.5229,  1.2469,  0.9707,  0.6942,  0.4174,  0.1403, -0.1371, -0.4147,
        -0.6926, -0.9708, -1.2492, -1.5280])


 65%|████████████████████████████████████████████████████▋                            | 65/100 [00:26<00:10,  3.47it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 66%|█████████████████████████████████████████████████████▍                           | 66/100 [00:27<00:09,  3.58it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 67%|██████████████████████████████████████████████████████▎                          | 67/100 [00:27<00:08,  3.73it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 68%|███████████████████████████████████████████████████████                          | 68/100 [00:27<00:08,  4.00it/s]

tensor([ 1.4274,  1.0204,  0.6130,  0.2051, -0.2031, -0.6118, -1.0208, -1.4303])


 69%|███████████████████████████████████████████████████████▉                         | 69/100 [00:27<00:07,  4.06it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 70%|████████████████████████████████████████████████████████▋                        | 70/100 [00:28<00:08,  3.72it/s]

tensor([ 1.5378,  1.2825,  1.0268,  0.7710,  0.5148,  0.2584,  0.0018, -0.2551,
        -0.5123, -0.7697, -1.0274, -1.2853, -1.5435])


 71%|█████████████████████████████████████████████████████████▌                       | 71/100 [00:28<00:07,  3.99it/s]

tensor([ 1.4274,  1.0204,  0.6130,  0.2051, -0.2031, -0.6118, -1.0208, -1.4303])


 72%|██████████████████████████████████████████████████████████▎                      | 72/100 [00:28<00:07,  3.92it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 73%|███████████████████████████████████████████████████████████▏                     | 73/100 [00:28<00:06,  4.08it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 74%|███████████████████████████████████████████████████████████▉                     | 74/100 [00:29<00:07,  3.54it/s]

tensor([ 1.5619,  1.3397,  1.1173,  0.8947,  0.6719,  0.4489,  0.2256,  0.0021,
        -0.2216, -0.4456, -0.6697, -0.8941, -1.1187, -1.3436, -1.5686])


 75%|████████████████████████████████████████████████████████████▊                    | 75/100 [00:29<00:06,  3.73it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 76%|█████████████████████████████████████████████████████████████▌                   | 76/100 [00:29<00:06,  3.70it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 77%|██████████████████████████████████████████████████████████████▎                  | 77/100 [00:29<00:06,  3.70it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 78%|███████████████████████████████████████████████████████████████▏                 | 78/100 [00:30<00:06,  3.35it/s]

tensor([ 1.5619,  1.3397,  1.1173,  0.8947,  0.6719,  0.4489,  0.2256,  0.0021,
        -0.2216, -0.4456, -0.6697, -0.8941, -1.1187, -1.3436, -1.5686])


 79%|███████████████████████████████████████████████████████████████▉                 | 79/100 [00:30<00:06,  3.35it/s]

tensor([ 1.5229,  1.2469,  0.9707,  0.6942,  0.4174,  0.1403, -0.1371, -0.4147,
        -0.6926, -0.9708, -1.2492, -1.5280])


 80%|████████████████████████████████████████████████████████████████▊                | 80/100 [00:30<00:05,  3.57it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 81%|█████████████████████████████████████████████████████████████████▌               | 81/100 [00:31<00:04,  3.83it/s]

tensor([ 1.4274,  1.0204,  0.6130,  0.2051, -0.2031, -0.6118, -1.0208, -1.4303])


 82%|██████████████████████████████████████████████████████████████████▍              | 82/100 [00:31<00:04,  3.67it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 83%|███████████████████████████████████████████████████████████████████▏             | 83/100 [00:31<00:04,  3.74it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 84%|████████████████████████████████████████████████████████████████████             | 84/100 [00:31<00:04,  3.69it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 85%|████████████████████████████████████████████████████████████████████▊            | 85/100 [00:32<00:04,  3.35it/s]

tensor([ 1.5619,  1.3397,  1.1173,  0.8947,  0.6719,  0.4489,  0.2256,  0.0021,
        -0.2216, -0.4456, -0.6697, -0.8941, -1.1187, -1.3436, -1.5686])


 86%|█████████████████████████████████████████████████████████████████████▋           | 86/100 [00:32<00:04,  3.49it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])
tensor([ 1.4274,  1.0204,  0.6130,  0.2051, -0.2031, -0.6118, -1.0208, -1.4303])

 87%|██████████████████████████████████████████████████████████████████████▍          | 87/100 [00:32<00:03,  3.81it/s]

 88%|███████████████████████████████████████████████████████████████████████▎         | 88/100 [00:32<00:03,  3.84it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 89%|████████████████████████████████████████████████████████████████████████         | 89/100 [00:33<00:02,  3.73it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 90%|████████████████████████████████████████████████████████████████████████▉        | 90/100 [00:33<00:02,  3.64it/s]

tensor([ 1.5229,  1.2469,  0.9707,  0.6942,  0.4174,  0.1403, -0.1371, -0.4147,
        -0.6926, -0.9708, -1.2492, -1.5280])


 91%|█████████████████████████████████████████████████████████████████████████▋       | 91/100 [00:33<00:02,  3.71it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 92%|██████████████████████████████████████████████████████████████████████████▌      | 92/100 [00:34<00:02,  3.51it/s]

tensor([ 1.5378,  1.2825,  1.0268,  0.7710,  0.5148,  0.2584,  0.0018, -0.2551,
        -0.5123, -0.7697, -1.0274, -1.2853, -1.5435])


 93%|███████████████████████████████████████████████████████████████████████████▎     | 93/100 [00:34<00:01,  3.56it/s]

tensor([ 1.5053e+00,  1.2051e+00,  9.0468e-01,  6.0393e-01,  3.0287e-01,
         1.5084e-03, -3.0015e-01, -6.0212e-01, -9.0438e-01, -1.2069e+00,
        -1.5098e+00])


 94%|████████████████████████████████████████████████████████████████████████████▏    | 94/100 [00:34<00:01,  3.70it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])


 95%|████████████████████████████████████████████████████████████████████████████▉    | 95/100 [00:34<00:01,  3.52it/s]

tensor([ 1.5378,  1.2825,  1.0268,  0.7710,  0.5148,  0.2584,  0.0018, -0.2551,
        -0.5123, -0.7697, -1.0274, -1.2853, -1.5435])


 96%|█████████████████████████████████████████████████████████████████████████████▊   | 96/100 [00:35<00:01,  3.73it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 97%|██████████████████████████████████████████████████████████████████████████████▌  | 97/100 [00:35<00:00,  3.89it/s]

tensor([ 1.4589e+00,  1.0950e+00,  7.3078e-01,  3.6618e-01,  1.2178e-03,
        -3.6411e-01, -7.2981e-01, -1.0959e+00, -1.4623e+00])


 98%|███████████████████████████████████████████████████████████████████████████████▍ | 98/100 [00:35<00:00,  3.62it/s]

tensor([ 1.5378,  1.2825,  1.0268,  0.7710,  0.5148,  0.2584,  0.0018, -0.2551,
        -0.5123, -0.7697, -1.0274, -1.2853, -1.5435])


 99%|████████████████████████████████████████████████████████████████████████████████▏| 99/100 [00:35<00:00,  3.87it/s]

tensor([ 1.4274,  1.0204,  0.6130,  0.2051, -0.2031, -0.6118, -1.0208, -1.4303])


100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [00:36<00:00,  2.76it/s]

tensor([ 1.4843,  1.1553,  0.8261,  0.4964,  0.1665, -0.1638, -0.4944, -0.8254,
        -1.1567, -1.4883])
